image:
  repository: registry.example.com/mobileapp/usersvc
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

env:
  APP_PORT: "8080"
  DB_DSN: "postgres://postgres:postgres@postgres:5432/appdb?sslmode=disable"
  OIDC_ISSUER: "http://keycloak:8081/realms/mobileapp"
  OIDC_AUDIENCE: "mobileapp-mobile"

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

podAnnotations: {}

nodeSelector: {}
tolerations: []
affinity: {}
