version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro

  usersvc:
    build:
      context: ../../
      dockerfile: infra/docker/usersvc.Dockerfile
    environment:
      APP_PORT: "8080"
      DB_DSN: "postgres://postgres:postgres@postgres:5432/appdb?sslmode=disable"
    ports: ["8080:8080"]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
