apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "usersvc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "usersvc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "usersvc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "usersvc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      containers:
        - name: usersvc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "usersvc.fullname" . }}-env
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
